const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={zip:null,root:'',catalog:{},index:[],detailCache:new Map(),character:null,currentCategory:'all',searchMode:'name',visibleRows:[]};
const abilityNames=['STR','CON','DEX','INT','WIS','CHA'];
const columnSets={power:['Name','Class','Type','Level','Usage'],feat:['Name','Tier','Prerequisite'],item:['Name','Level','Type'],monster:['Name','Level','Role','Size'],class:['Name','Role','Power Source'],race:['Name','Source'],theme:['Name','Source'],ritual:['Name','Level','Category']};
function blankCharacter(){return{schemaVersion:2,id:crypto.randomUUID(),name:'',level:1,race:'',className:'',paragonPath:'',epicDestiny:'',hpMax:20,hpCurrent:20,surgesMax:8,surgesCurrent:8,ac:10,fort:10,ref:10,will:10,speed:6,initiative:0,abilities:Object.fromEntries(abilityNames.map(x=>[x,10])),skills:'',notes:'',entries:[]}}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2200)}
function parseJsonpObject(text){const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start<0||end<0)throw new Error('No JSON object found');return JSON.parse(text.slice(start,end+1))}
function stripHtml(v){const d=document.createElement('div');d.innerHTML=String(v||'');return(d.textContent||'').replace(/\s+/g,' ').trim()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function extractFields(raw,category,id){const text=stripHtml(raw),parts=text.split(/\s{2,}|\t|\|/).map(x=>x.trim()).filter(Boolean);let name=parts[0]||id;const level=text.match(/\bLevel\s+(\d+|Minion|Solo|Elite)\b/i)?.[1]||'';const usage=text.match(/\b(At-Will|Encounter|Daily)\b/i)?.[1]||'';const tier=text.match(/\b(Heroic|Paragon|Epic)\s+Tier\b/i)?.[1]||'';const role=text.match(/\b(Artillery|Brute|Controller|Lurker|Skirmisher|Soldier|Leader)\b/i)?.[1]||'';const size=text.match(/\b(Tiny|Small|Medium|Large|Huge|Gargantuan)\b/i)?.[1]||'';const type=text.match(/\b(Attack|Utility|Feature|Armor|Weapon|Implement|Consumable|Wondrous Item)\b/i)?.[1]||'';return{id,category,raw,text,name:name.slice(0,140),fields:{Name:name,Class:parts[1]||'',Type:type||parts[2]||'',Level:level,Tier:tier,Prerequisite:parts.find(x=>/^Prerequisite/i.test(x))?.replace(/^Prerequisite:?\s*/i,'')||'',Usage:usage,Role:role,Size:size,'Power Source':'',Source:parts.at(-1)||'',Category:parts[2]||'',Summary:text.slice(0,220)}}}
async function loadZip(file){$('#statusText').textContent='Reading ZIP…';state.zip=await JSZip.loadAsync(file);const catalogPath=Object.keys(state.zip.files).find(n=>n.endsWith('/4e_database_files/catalog.js'));if(!catalogPath)throw new Error('This ZIP does not contain the Xenoth 4e database.');state.root=catalogPath.replace('catalog.js','');state.catalog=parseJsonpObject(await state.zip.file(catalogPath).async('text'));$('#catalogSummary').textContent=Object.entries(state.catalog).map(([k,v])=>`${k}: ${Number(v).toLocaleString()}`).join(' · ');$('#statusText').textContent='Indexing compendium…';const entries=[];for(const category of Object.keys(state.catalog)){const f=state.zip.file(`${state.root}${category}/_index.js`);if(!f)continue;const obj=parseJsonpObject(await f.async('text'));for(const [id,raw] of Object.entries(obj))entries.push(extractFields(raw,category,id))}state.index=entries;buildCategories();enableSearch();state.currentCategory='all';renderResults(entries.slice(0,250),entries.length);$('#statusText').textContent=`Ready: ${entries.length.toLocaleString()} indexed entries.`;toast('Xenoth compendium loaded')}
window.loadZip=loadZip;
function buildCategories(){const box=$('#act_list_pnl_category');box.innerHTML='';const cats=[['all',state.index.length],...Object.entries(state.catalog)];for(const [cat,count] of cats){const b=document.createElement('button');b.dataset.category=cat;b.innerHTML=`<span>${escapeHtml(cat==='all'?'All':cat[0].toUpperCase()+cat.slice(1))}</span><var>${Number(count).toLocaleString()}</var>`;b.onclick=()=>{state.currentCategory=cat;$$('#act_list_pnl_category button').forEach(x=>x.classList.toggle('active',x===b));doSearch()};box.append(b)}box.firstElementChild?.classList.add('active')}
function enableSearch(){['#act_list_txt_search','#act_list_btn_search_name','#act_list_btn_search_full'].forEach(s=>$(s).disabled=false)}
function doSearch(mode=state.searchMode){state.searchMode=mode;const q=$('#act_list_txt_search').value.trim().toLowerCase(),terms=q.split(/\s+/).filter(Boolean);let rows=state.index.filter(e=>state.currentCategory==='all'||e.category===state.currentCategory);if(terms.length)rows=rows.filter(e=>terms.every(t=>(mode==='name'?e.name:e.text).toLowerCase().includes(t)));rows.sort((a,b)=>score(b,q)-score(a,q)||a.name.localeCompare(b.name));renderResults(rows.slice(0,500),rows.length)}
function score(e,q){if(!q)return 0;const n=e.name.toLowerCase();return n===q?10:n.startsWith(q)?6:n.includes(q)?3:0}
function columnsFor(){const cat=state.currentCategory;if(cat!=='all'&&columnSets[cat])return columnSets[cat];if(cat==='all')return['Name','Category','Summary'];return['Name','Summary']}
function renderResults(rows,total=rows.length){state.visibleRows=rows;$('#act_list_lbl_showing').textContent=`Showing ${rows.length.toLocaleString()} of ${total.toLocaleString()}`;const cols=columnsFor(),head=$('#resultHead'),body=$('#resultBody');head.innerHTML='<tr>'+cols.map(c=>`<th>${escapeHtml(c)}<br><input class="txt_filter" data-col="${escapeHtml(c)}" type="search" placeholder="Filter"></th>`).join('')+'</tr>';body.innerHTML='';for(const e of rows){const tr=document.createElement('tr');tr.dataset.id=e.id;tr.innerHTML=cols.map(c=>`<td>${c==='Name'?`<a href="#">${escapeHtml(e.name)}</a>`:escapeHtml(c==='Category'?e.category:e.fields[c]||'')}</td>`).join('');tr.onclick=ev=>{ev.preventDefault();$$('#resultBody tr').forEach(x=>x.classList.toggle('selected',x===tr));showDetail(e)};body.append(tr)}$$('.txt_filter').forEach(i=>i.oninput=applyColumnFilters)}
function applyColumnFilters(){const filters=Object.fromEntries($$('.txt_filter').map(i=>[i.dataset.col,i.value.trim().toLowerCase()]));const rows=state.visibleRows.filter(e=>Object.entries(filters).every(([c,v])=>!v||String(c==='Category'?e.category:e.fields[c]||'').toLowerCase().includes(v)));const body=$('#resultBody'),cols=Object.keys(filters);body.innerHTML='';for(const e of rows){const tr=document.createElement('tr');tr.dataset.id=e.id;tr.innerHTML=cols.map(c=>`<td>${c==='Name'?`<a href="#">${escapeHtml(e.name)}</a>`:escapeHtml(c==='Category'?e.category:e.fields[c]||'')}</td>`).join('');tr.onclick=ev=>{ev.preventDefault();showDetail(e)};body.append(tr)}$('#act_list_lbl_showing').textContent=`Showing ${rows.length.toLocaleString()} filtered results`}
async function showDetail(e){const p=$('#act_list_pnl_preview');p.innerHTML='<p class="preview_hint">Loading full entry…</p>';try{const html=await getEntryHtml(e.category,e.id);p.innerHTML=`<div class="entry_toolbar"><button id="previewAdd">Add to character</button></div><div class="detail">${html||`<h1>${escapeHtml(e.name)}</h1><p>${escapeHtml(e.text)}</p>`}</div>`;$('#previewAdd').onclick=()=>addEntryToCharacter(e)}catch(err){p.innerHTML=`<h1>${escapeHtml(e.name)}</h1><p>${escapeHtml(e.text)}</p><p>${escapeHtml(err.message)}</p>`}}
async function getEntryHtml(category,id){const key=`${category}:${id}`;if(state.detailCache.has(key))return state.detailCache.get(key);if(!state.zip)return null;const paths=Object.keys(state.zip.files).filter(n=>n.startsWith(`${state.root}${category}/data`)&&n.endsWith('.js')).sort((a,b)=>(+a.match(/data(\d+)/)?.[1]||0)-(+b.match(/data(\d+)/)?.[1]||0));for(const p of paths){const text=await state.zip.file(p).async('text');if(!text.includes(`"${id}"`))continue;const obj=parseJsonpObject(text);if(obj[id]){state.detailCache.set(key,obj[id]);return obj[id]}}return null}
async function addEntryToCharacter(e){if(!state.character)state.character=blankCharacter();if(state.character.entries.some(x=>x.id===e.id))return toast('Already on character');toast(`Loading ${e.name}…`);const html=await getEntryHtml(e.category,e.id);state.character.entries.push({id:e.id,category:e.category,name:e.name,summary:e.text,used:false,html:html||`<h1>${escapeHtml(e.name)}</h1><p>${escapeHtml(e.text)}</p>`});renderCharacterEntries();toast(`${e.name} added with full entry`)}
function initAbilities(){const box=$('#abilities');box.innerHTML='';for(const a of abilityNames){const l=document.createElement('label');l.textContent=a;l.innerHTML+=`<input data-ability="${a}" type="number" value="10">`;box.append(l)}}
function renderCharacterEntries(){const box=$('#characterEntries');box.innerHTML='';if(!state.character.entries.length){box.innerHTML='<p>No powers, feats, items, or other entries added yet.</p>';return}const groups=state.character.entries.reduce((a,e)=>((a[e.category]??=[]).push(e),a),{});for(const [cat,items] of Object.entries(groups)){const g=document.createElement('section');g.className='entry_group';g.innerHTML=`<h3>${escapeHtml(cat[0].toUpperCase()+cat.slice(1))}</h3>`;for(const e of items){const d=document.createElement('article');d.className='character_entry'+(e.used?' used_entry':'');d.innerHTML=`<header><b>${escapeHtml(e.name)}</b><span class="no_print"><button data-use>${e.used?'Reset':'Use'}</button> <button data-remove>Remove</button></span></header><div class="entry_body detail">${e.html}</div>`;d.querySelector('[data-use]').onclick=()=>{e.used=!e.used;renderCharacterEntries()};d.querySelector('[data-remove]').onclick=()=>{state.character.entries=state.character.entries.filter(x=>x.id!==e.id);renderCharacterEntries()};g.append(d)}box.append(g)}}
function readForm(){const c=state.character;c.name=$('#characterName').value;c.level=+$('#level').value||1;for(const [k,id] of [['race','race'],['className','className'],['paragonPath','paragonPath'],['epicDestiny','epicDestiny'],['hpMax','hpMax'],['hpCurrent','hpCurrent'],['surgesMax','surgesMax'],['surgesCurrent','surgesCurrent'],['ac','ac'],['fort','fort'],['ref','ref'],['will','will'],['speed','speed'],['initiative','initiative'],['skills','skills'],['notes','notes']])c[k]=['skills','notes','race','className','paragonPath','epicDestiny'].includes(k)?$(`#${id}`).value:+$(`#${id}`).value||0;$$('[data-ability]').forEach(i=>c.abilities[i.dataset.ability]=+i.value||0);updateHeader();return c}
function writeForm(c){c.entries=(c.entries||[]).map(e=>({...e,html:e.html||`<h1>${escapeHtml(e.name)}</h1><p>${escapeHtml(e.summary||'')}</p>`}));state.character=c;$('#characterName').value=c.name||'';for(const [k,id] of [['level','level'],['race','race'],['className','className'],['paragonPath','paragonPath'],['epicDestiny','epicDestiny'],['hpMax','hpMax'],['hpCurrent','hpCurrent'],['surgesMax','surgesMax'],['surgesCurrent','surgesCurrent'],['ac','ac'],['fort','fort'],['ref','ref'],['will','will'],['speed','speed'],['initiative','initiative'],['skills','skills'],['notes','notes']])$(`#${id}`).value=c[k]??'';$$('[data-ability]').forEach(i=>i.value=c.abilities?.[i.dataset.ability]??10);updateHeader();renderCharacterEntries()}
function updateHeader(){const c=state.character;$('#sheetName').textContent=c.name||'Unnamed Hero';$('#sheetSummary').textContent=`Level ${c.level||1} ${[c.race,c.className].filter(Boolean).join(' ')||'Adventurer'}`}
function storage(){return JSON.parse(localStorage.getItem('xenothCharacters')||'[]')}
function saveCharacter(){readForm();const all=storage(),i=all.findIndex(x=>x.id===state.character.id);if(i>=0)all[i]=structuredClone(state.character);else all.push(structuredClone(state.character));localStorage.setItem('xenothCharacters',JSON.stringify(all));renderLibrary();toast('Character saved locally')}
function renderLibrary(){const all=storage(),box=$('#characterLibrary');$('#savedCount').textContent=all.length;if(!all.length){box.textContent='No saved characters yet.';return}box.innerHTML='';for(const c of all){const d=document.createElement('article');d.className='saved_card';d.innerHTML=`<h2>${escapeHtml(c.name||'Unnamed Hero')}</h2><p>Level ${c.level} ${escapeHtml([c.race,c.className].filter(Boolean).join(' '))}</p><button data-open>Open</button> <button data-delete>Delete</button>`;d.querySelector('[data-open]').onclick=()=>{writeForm(structuredClone(c));switchView('character')};d.querySelector('[data-delete]').onclick=()=>{localStorage.setItem('xenothCharacters',JSON.stringify(all.filter(x=>x.id!==c.id)));renderLibrary()};box.append(d)}}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function switchView(name){$$('.app_tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`))}
initAbilities();writeForm(blankCharacter());renderLibrary();
$('#zipInput').addEventListener('change',e=>loadZip(e.target.files[0]).catch(err=>{$('#statusText').textContent=err.message;toast(err.message)}));
$('#act_list_btn_search_name').onclick=()=>doSearch('name');$('#act_list_btn_search_full').onclick=()=>doSearch('full');$('#act_list_txt_search').onkeydown=e=>{if(e.key==='Enter')doSearch(state.searchMode)};$('#clearSearch').onclick=()=>{$('#act_list_txt_search').value='';doSearch()};
$$('.app_tab').forEach(t=>t.onclick=()=>switchView(t.dataset.view));$('#newCharacter').onclick=()=>writeForm(blankCharacter());$('#saveCharacter').onclick=saveCharacter;$('#characterName').oninput=()=>{state.character.name=$('#characterName').value;updateHeader()};$('#level').oninput=()=>{state.character.level=+$('#level').value||1;updateHeader()};
$('#shortRest').onclick=()=>{state.character.entries.forEach(e=>{if(/encounter/i.test(stripHtml(e.html)))e.used=false});renderCharacterEntries();toast('Encounter powers reset')};$('#extendedRest').onclick=()=>{readForm();state.character.hpCurrent=state.character.hpMax;state.character.surgesCurrent=state.character.surgesMax;state.character.entries.forEach(e=>e.used=false);writeForm(state.character);toast('Extended rest applied')};$('#spendSurge').onclick=()=>{readForm();if(state.character.surgesCurrent>0){state.character.surgesCurrent--;state.character.hpCurrent=Math.min(state.character.hpMax,state.character.hpCurrent+Math.floor(state.character.hpMax/4));writeForm(state.character)}};
$('#exportCharacter').onclick=()=>{readForm();download(`${(state.character.name||'character').replace(/[^a-z0-9]+/gi,'_')}.json`,JSON.stringify(state.character,null,2))};$('#importCharacter').onchange=async e=>{try{const c=JSON.parse(await e.target.files[0].text());if(!Array.isArray(c.entries))throw new Error('Unsupported character file');writeForm(c);toast('Character imported')}catch(err){toast(err.message)}};$('#printCharacter').onclick=()=>{readForm();window.print()};if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});