const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={zip:null,root:'',catalog:{},index:[],category:'all',searchMode:'full',detailCache:new Map(),character:null};
const abilities=['STR','CON','DEX','INT','WIS','CHA'];
function blankCharacter(){return{schemaVersion:2,id:crypto.randomUUID(),name:'New Character',level:1,race:'',className:'',paragonPath:'',epicDestiny:'',hpMax:20,hpCurrent:20,surgesMax:8,surgesCurrent:8,ac:10,fort:10,ref:10,will:10,speed:6,initiative:0,abilities:Object.fromEntries(abilities.map(a=>[a,10])),skills:'',notes:'',entries:[]}}
function toast(m){const n=document.createElement('div');n.className='toast';n.textContent=m;document.body.append(n);setTimeout(()=>n.remove(),2200)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function parseJsonp(t){const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<0)throw Error('Invalid compendium data');return JSON.parse(t.slice(a,b+1))}
function clean(v){return String(v||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function nameOf(text,cat){const tests={power:/^(.+?)(?=\s(?:[A-Z][\w' -]+\s(?:Attack|Utility|Feature)\s\d+|At-Will|Encounter|Daily)\b)/,feat:/^(.+?)(?=\s(?:Heroic|Paragon|Epic) Tier\b)/,item:/^(.+?)(?=\s(?:Level\s\d+|Heroic Level|Paragon Level|Epic Level|Artifact:|Armor|Weapon|Wondrous item)\b)/,monster:/^(.+?)(?=\s(?:Level\s\d+|Tiny|Small|Medium|Large|Huge|Gargantuan)\b)/};return (text.match(tests[cat]||/^(.{2,90}?)(?=\s[A-Z][a-z]+\s*:)/)?.[1]||text.split(/\.|:/)[0]||cat).trim().slice(0,110)}
function fields(e){const t=e.text;let m;if(e.category==='power'){m=t.match(/^(.*?)\s+(.+?)\s+(Attack|Utility|Feature)\s+(\d+)/);return{Name:e.name,Class:m?.[2]||'',Type:m?.[3]||'',Level:m?.[4]||'',Usage:(t.match(/\b(At-Will|Encounter|Daily)\b/)||[])[1]||''}}if(e.category==='feat')return{Name:e.name,Tier:(t.match(/\b(Heroic|Paragon|Epic) Tier\b/)||[])[1]||'',Prerequisite:(t.match(/Prerequisite\s*:\s*(.*?)(?=Benefit\s*:|$)/)||[])[1]||''};if(e.category==='item')return{Name:e.name,Level:(t.match(/\b(?:Level|Lvl)\s*(\d+)/i)||[])[1]||'',Type:(t.match(/\b(Armor|Weapon|Wondrous item|Implement|Consumable|Artifact)\b/i)||[])[1]||''};if(e.category==='monster')return{Name:e.name,Level:(t.match(/\bLevel\s*(\d+)/i)||[])[1]||'',Role:(t.match(/\b(Minion|Skirmisher|Soldier|Brute|Controller|Artillery|Lurker|Solo|Elite)\b/i)||[])[1]||'',Size:(t.match(/\b(Tiny|Small|Medium|Large|Huge|Gargantuan)\b/)||[])[1]||''};return{Name:e.name,Summary:t.slice(e.name.length).trim().slice(0,220)}}
async function loadZip(file){$('#statusText').textContent=' Reading ZIP…';state.zip=await JSZip.loadAsync(file);const cp=Object.keys(state.zip.files).find(n=>n.endsWith('/4e_database_files/catalog.js'));if(!cp)throw Error('This ZIP does not contain the Xenoth database.');state.root=cp.replace('catalog.js','');state.catalog=parseJsonp(await state.zip.file(cp).async('text'));const entries=[];for(const cat of Object.keys(state.catalog)){const f=state.zip.file(`${state.root}${cat}/_index.js`);if(!f)continue;const obj=parseJsonp(await f.async('text'));for(const[id,v]of Object.entries(obj)){const text=clean(v);entries.push({id,category:cat,text,name:nameOf(text,cat)})}}state.index=entries;renderCategories();enableSearch();$('#statusText').textContent=` ${entries.length.toLocaleString()} entries indexed.`;renderResults(entries.slice(0,250),entries.length);toast('Compendium ready')}
window.loadZip=loadZip;
function renderCategories(){const box=$('#categoryTabs');box.innerHTML='';[['all',state.index.length],...Object.entries(state.catalog)].forEach(([cat,count])=>{const b=document.createElement('button');b.textContent=`${cat} (${Number(count).toLocaleString()})`;b.className=cat===state.category?'cat-active':'';b.onclick=()=>{state.category=cat;renderCategories();search()};box.append(b)})}
function enableSearch(){['#searchInput','#searchName','#searchFull'].forEach(s=>$(s).disabled=false)}
function search(mode=state.searchMode){state.searchMode=mode;const q=$('#searchInput').value.trim().toLowerCase(),terms=q.split(/\s+/).filter(Boolean);let rows=state.index.filter(e=>(state.category==='all'||e.category===state.category)&&terms.every(x=>(mode==='name'?e.name:e.text).toLowerCase().includes(x)));rows.sort((a,b)=>rank(b,q)-rank(a,q)||a.name.localeCompare(b.name));renderResults(rows.slice(0,500),rows.length)}
function rank(e,q){if(!q)return 0;const n=e.name.toLowerCase();return n===q?20:n.startsWith(q)?10:n.includes(q)?5:0}
function columnsFor(rows){if(state.category==='all')return['Name','Category','Summary'];const keys=new Set();rows.slice(0,50).forEach(e=>Object.keys(fields(e)).forEach(k=>keys.add(k)));return[...keys]}
function renderResults(rows,total=rows.length){$('#resultCount').textContent=`Showing ${Math.min(rows.length,total).toLocaleString()} of ${total.toLocaleString()}`;const wrap=$('#resultTableWrap');if(!rows.length){wrap.className='empty-state';wrap.textContent='No matching entries.';return}wrap.className='';const cols=columnsFor(rows);const table=document.createElement('table');table.className='results-table';table.innerHTML=`<thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th></th></tr></thead><tbody></tbody>`;for(const e of rows){const f=state.category==='all'?{Name:e.name,Category:e.category,Summary:e.text.slice(e.name.length).trim().slice(0,180)}:fields(e);const tr=document.createElement('tr');tr.innerHTML=cols.map((c,i)=>`<td class="${i===0?'entry-link':''}">${esc(f[c]||'')}</td>`).join('')+`<td><button class="add-entry">Add</button></td>`;tr.onmouseenter=()=>preview(e,tr);tr.onclick=ev=>{if(ev.target.closest('.add-entry'))addEntry(e);else preview(e,tr)};table.tBodies[0].append(tr)}wrap.replaceChildren(table)}
async function preview(e,tr){$$('.results-table tr').forEach(r=>r.classList.remove('selected'));tr?.classList.add('selected');$('#detail').innerHTML='<div class="preview_hint">Loading complete entry…</div>';const html=await getEntryHtml(e.category,e.id);$('#detail').innerHTML=`<div class="no-print"><button id="previewAdd">Add to Character</button></div>${html||`<h1>${esc(e.name)}</h1><p>${esc(e.text)}</p>`}`;$('#previewAdd').onclick=()=>addEntry(e)}
async function getEntryHtml(cat,id){const key=`${cat}:${id}`;if(state.detailCache.has(key))return state.detailCache.get(key);for(const p of Object.keys(state.zip?.files||{}).filter(n=>n.startsWith(`${state.root}${cat}/data`)&&n.endsWith('.js')).sort((a,b)=>(+a.match(/data(\d+)/)?.[1]||0)-(+b.match(/data(\d+)/)?.[1]||0))){const t=await state.zip.file(p).async('text');if(!t.includes(`"${id}"`))continue;const o=parseJsonp(t);if(o[id]){state.detailCache.set(key,o[id]);return o[id]}}return''}
async function addEntry(e){if(state.character.entries.some(x=>x.id===e.id))return toast('Already on character');toast(`Loading ${e.name}…`);const html=await getEntryHtml(e.category,e.id);state.character.entries.push({id:e.id,category:e.category,name:e.name,summary:e.text,html:html||`<h1>${esc(e.name)}</h1><p>${esc(e.text)}</p>`,used:false});renderCharacter();toast(`${e.name} added with full entry`)}
function initAbilities(){const box=$('#abilities');box.innerHTML='';abilities.forEach(a=>{const l=document.createElement('label');l.innerHTML=`${a}<input data-ability="${a}" type="number" value="10">`;box.append(l)})}
function readCharacter(){const c=state.character;c.name=$('#characterName').value||$('#sheetNameInput').value||'New Character';c.level=+$('#level').value||+$('#sheetLevel').value||1;['race','className','paragonPath','epicDestiny','skills','notes'].forEach(k=>c[k]=$(`#${k}`).value);['hpMax','hpCurrent','surgesMax','surgesCurrent','ac','fort','ref','will','speed','initiative'].forEach(k=>c[k]=+$(`#${k}`).value||0);$$('[data-ability]').forEach(i=>c.abilities[i.dataset.ability]=+i.value||0);syncNames();return c}
function writeCharacter(c){state.character={...blankCharacter(),...c,abilities:{...blankCharacter().abilities,...c.abilities},entries:c.entries||[]};$('#characterName').value=$('#sheetNameInput').value=state.character.name;$('#level').value=$('#sheetLevel').value=state.character.level;['race','className','paragonPath','epicDestiny','skills','notes','hpMax','hpCurrent','surgesMax','surgesCurrent','ac','fort','ref','will','speed','initiative'].forEach(k=>$(`#${k}`).value=state.character[k]??'');$$('[data-ability]').forEach(i=>i.value=state.character.abilities[i.dataset.ability]);renderCharacter()}
function syncNames(){const c=state.character;$('#characterName').value=$('#sheetNameInput').value=c.name;$('#level').value=$('#sheetLevel').value=c.level;$('#sheetSummary').textContent=`Level ${c.level} ${[c.race,c.className].filter(Boolean).join(' ')||'Adventurer'}`}
function renderCharacter(){syncNames();$('#characterSummary').innerHTML=`<b>${esc(state.character.name)}</b><br>Level ${state.character.level} · ${state.character.entries.length} entries`;const groups=state.character.entries.reduce((a,e)=>((a[e.category]??=[]).push(e),a),{});const side=$('#characterEntries'),full=$('#fullCharacterEntries');side.innerHTML='';full.innerHTML='';for(const[cat,items]of Object.entries(groups)){const g=document.createElement('div');g.className='char-list';g.innerHTML=`<h3>${esc(cat)} (${items.length})</h3>`;for(const e of items){const card=document.createElement('div');card.className=`char-card ${e.used?'used':''}`;card.innerHTML=`<div class="char-card-head"><span>${esc(e.name)}</span><span><button data-use>${e.used?'Reset':'Use'}</button><button data-remove>×</button></span></div><div class="char-card-body">${e.html}</div>`;card.querySelector('[data-use]').onclick=()=>{e.used=!e.used;renderCharacter()};card.querySelector('[data-remove]').onclick=()=>{state.character.entries=state.character.entries.filter(x=>x.id!==e.id);renderCharacter()};g.append(card);const f=document.createElement('section');f.className=`full-entry ${e.used?'used':''}`;f.innerHTML=`<div class="full-entry-toolbar no-print"><button data-use>${e.used?'Reset':'Mark Used'}</button><button data-remove>Remove</button></div><div class="entry-body">${e.html}</div>`;f.querySelector('[data-use]').onclick=()=>{e.used=!e.used;renderCharacter()};f.querySelector('[data-remove]').onclick=()=>{state.character.entries=state.character.entries.filter(x=>x.id!==e.id);renderCharacter()};full.append(f)}side.append(g)}if(!state.character.entries.length){side.innerHTML='<p>No entries selected.</p>';full.innerHTML='<p>No compendium entries selected.</p>'}}
function saved(){return JSON.parse(localStorage.getItem('xenothCharacters')||'[]')}
function save(){readCharacter();const all=saved(),i=all.findIndex(x=>x.id===state.character.id);i<0?all.push(structuredClone(state.character)):all[i]=structuredClone(state.character);localStorage.setItem('xenothCharacters',JSON.stringify(all));renderLibrary();toast('Character saved')}
function renderLibrary(){const box=$('#characterLibrary');box.innerHTML='';for(const c of saved()){const a=document.createElement('article');a.className='saved-card';a.innerHTML=`<h2>${esc(c.name)}</h2><p>Level ${c.level} ${esc([c.race,c.className].filter(Boolean).join(' '))}</p><button data-open>Open</button> <button data-delete>Delete</button>`;a.querySelector('[data-open]').onclick=()=>{writeCharacter(structuredClone(c));showView('character')};a.querySelector('[data-delete]').onclick=()=>{localStorage.setItem('xenothCharacters',JSON.stringify(saved().filter(x=>x.id!==c.id)));renderLibrary()};box.append(a)}}
function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`${v}View`));$('#topHeader').style.display=v==='compendium'?'flex':'none';window.scrollTo(0,0)}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
initAbilities();writeCharacter(blankCharacter());renderLibrary();
$('#zipInput').onchange=e=>e.target.files[0]&&loadZip(e.target.files[0]).catch(x=>toast(x.message));$('#searchName').onclick=()=>search('name');$('#searchFull').onclick=()=>search('full');$('#searchInput').onkeydown=e=>e.key==='Enter'&&search(state.searchMode);$('#newCharacter').onclick=()=>writeCharacter(blankCharacter());$('#saveCharacter').onclick=$('#saveCharacterSheet').onclick=save;$('#openSheet').onclick=()=>{readCharacter();showView('character')};$('#backToCompendium').onclick=$('#libraryBack').onclick=()=>showView('compendium');$('#characterName').oninput=e=>{state.character.name=e.target.value;syncNames()};$('#level').oninput=e=>{state.character.level=+e.target.value||1;syncNames()};$('#sheetNameInput').oninput=e=>{state.character.name=e.target.value;syncNames()};$('#sheetLevel').oninput=e=>{state.character.level=+e.target.value||1;syncNames()};$('#shortRest').onclick=()=>{state.character.entries.filter(e=>/encounter/i.test(e.html+e.summary)).forEach(e=>e.used=false);renderCharacter()};$('#extendedRest').onclick=()=>{readCharacter();state.character.hpCurrent=state.character.hpMax;state.character.surgesCurrent=state.character.surgesMax;state.character.entries.forEach(e=>e.used=false);writeCharacter(state.character)};$('#spendSurge').onclick=()=>{readCharacter();if(state.character.surgesCurrent){state.character.surgesCurrent--;state.character.hpCurrent=Math.min(state.character.hpMax,state.character.hpCurrent+Math.floor(state.character.hpMax/4));writeCharacter(state.character)}};$('#exportCharacter').onclick=()=>{readCharacter();download(`${state.character.name.replace(/\W+/g,'_')}.json`,JSON.stringify(state.character,null,2))};$('#importCharacter').onchange=async e=>{try{writeCharacter(JSON.parse(await e.target.files[0].text()));toast('Imported')}catch{toast('Invalid character file')}};$('#printCharacter').onclick=$('#printCharacterSheet').onclick=()=>{readCharacter();showView('character');setTimeout(()=>window.print(),100)};if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});